### ISSUE TITLE
Jamf Uploader Feature request: Optionally disable XML escaping for template variable substitution

### ISSUE THREAD

**Issue by davidbpirie** [autopkg/grahampugh-recipes#122]
I would like the ability to disable XML escaping when an XML template has variable substitution performed in the Jamf Uploader processors, namely:

- JamfAccountUploader
- JamfMacAppUploader
- JamfPatchUploader
- JamfPolicyUploader
- JamfSoftwareRestrictionUploader

My use case is to reduce the number of templates I need to maintain in our environment and move more flexibility into our AutoPkg recipe overrides, for example including 2 computer groups and corresponding XML tags directly in a single variable that is substituted into the template.

I will submit a PR with my suggested implementation.

**Comment by grahampugh** [comment]
Hi David. Please could you explain how disabling XML escaping would help reduce the number of templates required? I don't see the connection. Also, any Issue or PR relating to JamfUploader processors should be opened at grahampugh/jamf-upload rather than here. I do not accept any PRs in this repo (I know it's probably hard to find, but that policy is documented in the README here: https://github.com/autopkg/grahampugh-recipes/tree/main/JamfUploaderProcessors). Thanks!

**Comment by davidbpirie** [comment]
Hi Graham,

First, sorry for the incorrect PR - I even now remember reading that in your readme when I started using Jamf Uploader last year.
As for the benefits of disabling XML escaping, I will move my changes to a proper PR and better document there.
