### ISSUE TITLE
CLCGenomicsWorkbench.download.recipe.yaml

### ISSUE THREAD

**Issue by andreilabin** [autopkg/grahampugh-recipes#136]
Intel- and ARM64-Versions are now both offered, with the arch-identifier between version-number and .dmg

**Comment by andreilabin** [comment]
i've made new recipes for [Intel](https://github.com/eth-its/autopkg-mac-recipes-yaml/blob/main/Download_Recipes/CLCGenomicsWorkbench-intel.download.recipe.yaml) and [arm64](https://github.com/eth-its/autopkg-mac-recipes-yaml/blob/main/Download_Recipes/CLCGenomicsWorkbench-arm64.download.recipe.yaml)-versions instead of forking this and making a pull request. Maybe you come up with a more elegant way to incorporate architecture in one download recipe.

**Comment by grahampugh** [comment]
Hi Andrei, thanks for the tip. I've adapted the recipe to include an `%ARCH%` Input variable. I've deliberately made it separate to the `%PLATFORM%` keys you have in the ETH .pkg recipe since the values differ. You could either continue to use your separate recipes, or revert to this recipe and supply the `%ARCH%` key in your `.jamf` recipes.
