### ISSUE TITLE
AdoptOpenJDK11.download.recipe fails to download due to json output change in api source

### ISSUE THREAD

**Issue by eithor** [autopkg/grahampugh-recipes#59]
The AdoptOpenJDK11.download.recipe now fails. It looks like the URL in the downloaded json from the api has changed format - and the re_pattern is no longer matching. If I'm seeing this correct then the 'AdoptOpenJDK' part should be replaced with 'adoptium' in the re_pattern.

**Comment by eshirk** [comment]
I believe this format change is also affecting the AdoptOpenJDK8_Signed.download.recipe.

**Comment by grahampugh** [comment]
It looks like AdoptOpenJDK is (or has already) rebranding to Eclipse, and the API has completely changed. v2 is deprecated. I'm looking at v3 (https://api.adoptopenjdk.net/q/swagger-ui/#) now, but I need to understand the output better. 

For example, when I choose to download the latest adoptopenjdk 11 installer, I get the package for Eclipse Temurin.

**Comment by eithor** [comment]
I understand that Eclipse Temurin is just the build infrastructure name. See https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/

If you go directly (no api) to adoptium.net or the old adoptopenjdk.net the URL in the download link includes "temurin" in the URL path.

**Comment by grahampugh** [comment]
@eithor I have created new recipes for Eclipse Termurin, and deprecated all the AdoptOpenJDK recipes, since it appears there will be no more updates using that name. 

Note that I am not migrating the Munki recipes. Somebody else will have to create Munki recipes for Eclipse Temurin if they are interested. 

Also, the OpenJ9 builds are apparently not allowed to be distributed by Eclipse, and can only be obtained from IBM. Again, those will need different recipes at this time, though the adoptium v3 API appears to have been designed to be able to distribute them in the future, so I have made all the download recipes overridable with different implementations and vendors.
